# File: ios/Podfile

require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '17.0'

install! 'cocoapods', :disable_input_output_paths => true
prepare_react_native_project!

target 'RedCarRummy' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Flipper is off by default. To enable, uncomment below and add the flipper require:
  # require_relative '../node_modules/react-native/scripts/react_native_flipper'
  # use_flipper!()
end

post_install do |installer|
  react_native_post_install(installer)
end
